apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: todo-ui
  labels:
    app.kubernetes.io/part-of: todos-app
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: todo-ui
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"todos-app","apps.tanzu.vmware.com/has-tests":"false","apps.tanzu.vmware.com/workload-type":"web"},"name":"todo-ui","namespace":"demos"},"spec":{"build":{"env":[{"name":"BP_NODE_RUN_SCRIPTS","value":"build"},{"name":"BP_WEB_SERVER","value":"httpd"},{"name":"BP_WEB_SERVER_ROOT","value":"dist"},{"name":"BP_WEB_SERVER_ENABLE_PUSH_STATE","value":"true"}]},"params":[{"name":"clusterBuilder","value":"builder-for-web-servers"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/odedia/todo-ui"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: todos-app
        apps.tanzu.vmware.com/has-tests: "false"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: todo-ui
    spec:
      containers:
      - image: harbor.apps.cf.tanzutime.com/apps/todo-ui-demos@sha256:5644786270e6ff39f2ac96cc5a3c3181c640be90641e0cef174bfef13c893dee
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

